### ISSUE TITLE
你好，非常感谢提供思路

### ISSUE THREAD

**Issue by ReverseScale** [Danny1451/PushTest#1]
我之前也一直想着用推送+语音播报的方式实现类似支付宝收钱的功能，看到你的Demo很是兴奋，只是，能否将“iOS 10 来点不一样的推送 (2) - 语言提示”的Demo中操作实现的方法写出来，我下载了这个Demo，但是并不能查看语音播报是什么样子..望不吝赐教

**Comment by Danny1451** [comment]
因为涉及到推送证书的问题，所以我的 demo 并不是运行就能使用的。但是代码已经在 demo 里了，只要你配置下你自己的推送证书就可以了。

**Comment by ReverseScale** [comment]
好的，了解了，非常感谢
